# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/clip-plot',
                'doc_host': 'https://fr1ll.github.io',
                'git_url': 'https://github.com/fr1ll/clip-plot',
                'lib_path': 'clip_plot'},
  'syms': {'clip_plot.core': {'clip_plot.core.foo': ('core.html#foo', 'clip_plot/core.py')}}}