# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_from_tables.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/08_from_tables.ipynb 3
import pandas as pd
import pyarrow.parquet as pq
from pathlib import Path
