"""Get image and vector locations, and optionally metadata, from one or more table inputs"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_from_tables.ipynb.

# %% auto #0
__all__ = ['cat_tables', 'glob_to_tables', 'table_to_meta']

# %% ../nbs/08_from_tables.ipynb #4601e568
from glob import glob
from pathlib import Path

import polars as pl

# %% ../nbs/08_from_tables.ipynb #5e4362ee
def cat_tables(table_paths: list[Path]) -> pl.DataFrame:
    '''
    read and concatenate tables from list of paths
    '''
    extensions = {p.suffix.lower() for p in table_paths}
    if extensions not in [{".csv"}, {".parquet"}]:
        raise ValueError(f"All tables must have same extension, either .csv or .parquet. Got: {extensions}")
    if extensions == {".csv"}:
        return pl.concat((pl.read_csv(t) for t in table_paths), how="diagonal_relaxed")
    elif extensions == {".parquet"}:
        return pl.concat((pl.read_parquet(t) for t in table_paths), how="diagonal_relaxed")

# %% ../nbs/08_from_tables.ipynb #a1034456
def glob_to_tables(pattern: str) -> pl.DataFrame:
    '''
    expand a glob of tables, read in the tables,
    and output as concatenated DataFrame
    '''
    table_paths = [Path(p) for p in glob(pattern, recursive=True)]
    if len(table_paths) == 0:
        raise FileNotFoundError("No tables matched.")
    return cat_tables(table_paths)


# %% ../nbs/08_from_tables.ipynb #2bba805e
def table_to_meta(table: pl.DataFrame) -> tuple[list, list]:
    '''convert table to metadata columns and list'''
    # viewer expects filename column
    table = table.rename({"image_filename": "filename"})
    meta_columns = set(table.columns) - {"image_path", "hidden_vectors"}
    # convert to list as pandas does not let you index with a set
    meta_columns = list(meta_columns)
    df_meta = table[meta_columns]
    return meta_columns, df_meta.to_dicts()
