# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_from_tables.ipynb.

# %% auto 0
__all__ = ['glob_to_tables']

# %% ../nbs/08_from_tables.ipynb 3
import pandas as pd
import pyarrow.parquet as pq
from pathlib import Path
from glob import glob

# %% ../nbs/08_from_tables.ipynb 4
def glob_to_tables(pattern: str) -> pd.DataFrame:
    '''
    expand a glob of tables, read in the tables,
    and output as concatenated DataFrame
    '''
    table_paths = [Path(p) for p in glob(pattern, recursive=True)]
    if len(table_paths) == 0: raise FileNotFoundError("No tables matched.")

    extensions = {p.suffix for p in table_paths}
    if extensions == {".csv"}:
        dataset = [pd.read_csv(t) for t in table_paths]
        return pd.concat(dataset, ignore_index=True)
    elif extensions == {".parquet"}:
        dataset = pq.ParquetDataset(table_paths)
        return dataset.read().to_pandas()
    else:
        raise ValueError(f"Unsupported table extensions: {extensions}")

