# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_main.ipynb.

# %% auto #0
__all__ = ['embed_im_cli', 'project_tables_cli']

# %% ../nbs/00_main.ipynb #d405f834
from pydantic_settings import BaseSettings, CliApp

from .configuration import Cfg
from .pipelines import embed_images_pipeline, project_images_pipeline


# %% ../nbs/00_main.ipynb #61b2efdb
def embed_im_cli():
    cfg: BaseSettings = CliApp.run(Cfg)
    embed_images_pipeline(cfg.paths.images,
                     cfg.model,
                     cfg.paths.metadata,
                     cfg.paths.output_dir,
                     cfg.paths.table_format,
                     cfg.paths.table_id,
                )
    return None

# %% ../nbs/00_main.ipynb #398ebba7
def project_tables_cli():
    cfg: BaseSettings = CliApp.run(Cfg)
    project_images_pipeline(plot_id=cfg.plot_id,
                            output_dir=cfg.paths.output_dir,
                            model=cfg.model,
                            viewer_opts=cfg.view_opts,
                            umap_spec=cfg.umap_spec,
                            cluster_spec=cfg.cluster_spec,
                            image_opts=cfg.image_opts,
                            images=cfg.paths.images,
                            tables=cfg.paths.tables,
                            metadata=cfg.paths.metadata,
                            image_path_col=cfg.image_path_col,
                            vectors_col=cfg.vectors_col,
                )
    return None
