# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_embeddings.ipynb.

# %% auto 0
__all__ = ['images_from_paths', 'images_iterator', 'embed_images', 'get_embeddings']

# %% ../../nbs/04_embeddings.ipynb 2
from pathlib import Path

import numpy as np
import torch
from PIL import Image
from tqdm.auto import tqdm
from transformers import pipeline

from .utils import timestamp


# %% ../../nbs/04_embeddings.ipynb 4
def images_from_paths(pathlist):
    return (Image.open(p.as_posix()).convert("RGB").copy() for p in pathlist)

# %% ../../nbs/04_embeddings.ipynb 5
def images_iterator(ImageEngine):
    return (img.original for img in ImageEngine)

# %% ../../nbs/04_embeddings.ipynb 6
def embed_images(imagepaths : list[Path],
                 model_name : str = "timm/convnext_tiny.dinov3_lvd1689m",
                #  batch_size : int = 4
                 ) -> np.ndarray:
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Device for inference: {device}")
    pipe = pipeline(task="image-feature-extraction",
                    model=model_name, device=device, pool=True, use_fast=True)

    print(timestamp(), f"Creating embeddings using {model_name}")
    embeddings = []
    imagepath_strs = [Path(p).as_posix() for p in imagepaths]

    # for out in tqdm(pipe(imagepath_strs, batch_size=batch_size), total=len(imagepath_strs)):
    #     embeddings += out
    for p in tqdm(imagepath_strs): # giving up on progress bar with batch size
        embeddings += pipe(p)

    print(timestamp(), "Done creating embeddings.")

    return np.array(embeddings)

# %% ../../nbs/04_embeddings.ipynb 7
def get_embeddings(image_paths: list[Path],
                   model_name : str = "timm/convnext_tiny.dinov3_lvd1689m",
                #    batch_size : int = 4
                   ) -> np.ndarray:
    return embed_images(image_paths, model_name=model_name,
    # batch_size=batch_size
    )
