# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_utils.ipynb.

# %% auto 0
__all__ = ['FILE_NAME', 'get_version', 'round_floats', 'is_number', 'timestamp', 'get_json_path', 'write_json', 'read_json',
           'copytree_agnostic', 'clean_filename']

# %% ../../nbs/01_utils.ipynb 2
import os
import sys
import json
from typing import Any
import datetime
from shutil import copytree
from urllib.parse import unquote

from pathlib import Path

# %% ../../nbs/01_utils.ipynb 3
FILE_NAME = "filename"  # Filename name key

# %% ../../nbs/01_utils.ipynb 4
def get_version():
    """
    Return the version of clipplot installed
    Hardcoded for now
    """
    # return pkg_resources.get_distribution("clipplot").version
    return "0.0.1"

# %% ../../nbs/01_utils.ipynb 6
def round_floats(obj, digits=5):
    """Return 2D array obj with rounded float precision"""
    return [[round(float(j), digits) for j in i] for i in obj]

# %% ../../nbs/01_utils.ipynb 7
def is_number(s: str) -> bool:
    try:
        int(s)
        return True
    except ValueError:
        return False

# %% ../../nbs/01_utils.ipynb 9
def timestamp():
    """Return a string for printing the current time"""
    return str(datetime.datetime.now()) + ":"

# %% ../../nbs/01_utils.ipynb 11
def get_json_path(data_dir: Path, subdir: str | None,
                  plot_id: str | None, filename: str) -> Path:
    """
    Combine path and add json extension
    """
    output_dir = data_dir
    if subdir:
        output_dir = data_dir / subdir
    if plot_id:
        filename = f"{filename}__{plot_id}"
    return output_dir/(filename + ".json") # don't use with_suffix, it chops names with decimals

# %% ../../nbs/01_utils.ipynb 13
def write_json(output_path: Path, object: Any):
    """
    Write json object `obj` to disk and return the path to that file
    """
    #| export

    def _convert_paths(obj):
        if isinstance(obj, Path):
            return str(obj)
        # let json handle other types
        raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as out:
        json.dump(object, out, default=_convert_paths, indent=2)

# %% ../../nbs/01_utils.ipynb 14
def read_json(path: Path) -> dict:
    with path.open("r") as f:
        return json.load(f)

# %% ../../nbs/01_utils.ipynb 16
def copytree_agnostic(a,b):
    if sys.version_info.major >=3 and sys.version_info.minor >=8:
        copytree(a, b, dirs_exist_ok=True)
    else:
        from distutils.dir_util import copy_tree
        copy_tree(a, b)

# %% ../../nbs/01_utils.ipynb 18
def clean_filename(s: str) -> str:
    """Given a string that points to a filename, return a clean filename
    """
    s = unquote(os.path.basename(s))
    invalid_chars = '<>:;,"/\\|?*[]'
    for i in invalid_chars:
        s = s.replace(i, "")
    return s
