# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06_web_config.ipynb.

# %% auto #0
__all__ = ['get_clip_plot_root', 'replace_web_strings', 'byo_logo', 'copy_web_assets']

# %% ../../nbs/06_web_config.ipynb #774c7347
from pathlib import Path
from shutil import copy

from . import utils
from .utils import get_version

# %% ../../nbs/06_web_config.ipynb #db43ad4c
def get_clip_plot_root() -> Path:
    """Return the module root that contains the bundled web assets."""
    starts = [Path(utils.__file__).resolve(), Path.cwd().resolve()]
    if "__file__" in globals():
        starts.append(Path(__file__).resolve())

    for start in starts:
        current = start if start.is_dir() else start.parent
        for path in (current, *current.parents):
            if (path / "src/clip_plot/web").exists():
                return path / "src"
            if (path / "clip_plot/web").exists():
                return path

    raise FileNotFoundError("Could not find bundled clip_plot web assets")

# %% ../../nbs/06_web_config.ipynb #cfa71671
def replace_web_strings(web_dir: Path, from_to: dict):
    '''sequentially replace strings based on dict'''
    for i in ["index.html", "assets/js/tsne.js"]:
        f = web_dir / i
        t = f.read_text()
        for k, v in from_to.items():
            t = t.replace(k, v)
        f.write_text(t)


# %% ../../nbs/06_web_config.ipynb #de05eeb7
def byo_logo(web_dir: Path, logo_path: Path):
    '''copy logo into web folder and replace reference in index.html'''
    logo_dest = web_dir / "assets/images" / logo_path.name
    copy(logo_path, logo_dest)
    replace_web_strings(web_dir, {"cp_logo.png": logo_path.name,
                                  "clip-plot logo": "Custom logo"
                               })

# %% ../../nbs/06_web_config.ipynb #12baba30
def copy_web_assets(output_dir: Path, tagline: str | None, logo: Path | None) -> None:
    """
    Copy the /web directory from the clipplot source to the users cwd.
    Copies version number into assets.
    """
    copy_root_dir = get_clip_plot_root()
    src = copy_root_dir / "clip_plot/web"

    # resolve will handle cases with ../ in the path
    dest = Path.cwd() / output_dir.resolve()
    utils.copytree_agnostic(src.as_posix(), dest.as_posix())

    replace_web_strings(dest, {"VERSION_NUMBER": get_version()})

    if tagline:
        replace_web_strings(dest, {"Image Fields in a Local Collection": tagline})

    if logo:
        logo_resolved = Path.cwd() / logo.resolve()
        byo_logo(dest, logo_resolved)

